-- dummy kategori
/*
INSERT INTO Kategori (nama_kategori)
VALUES
	('Romance'),
	('Action'),
	('Comedy'),
	('Fantasy'),
	('Crime'),
	('Horror'),
	('Thriller'),
	('Religion'),
	('Biography'),
	('Physics'),
	('Geography'),
	('Music'),
	('Sports'),
	('Video Game'),
	('Information Technology'),
	('Engineering'),
	('Mathematics'),
	('Computer Science'),
	('Social Science'),
	('Data Science'),
	('Astrophysics'),
	('Chemistry'),
	('Climate Change'),
	('Electronics'),
	('Health'),
	('Foods'),
	('Music'),
	('Politics'),
	('Content Creating'),
	('Business'),
	('Conspiracy'),
	('Art'),
	('Fashion'),
	('Beauty'),
	('Psychology'),
	('Japanese'),
	('Korean'),
	('Photography'),
	('History'),
	('Fanfiction'),
	('Science Fiction'),
	('Traveling'),
	('Law'),
	('Accounting'),
	('Investment'),
	('Movie'),
	('Architectural'),
	('Education'),
	('Home Living'),
	('Family')
*/