GO
USE Perpustakaan

--negara
INSERT INTO Negara (nama_negara) 
VALUES 
	('Afganistan'),
	('Afrika Selatan'),
	('Afrika Tengah'),
	('Albania'),
	('Amerika Serikat'),
	('Australia'),
	('Arab Saudi'),
	('Argentina'),
	('Austria'),
	('Belanda'),
	('Belgia'),
	('Brasil'),
	('Brunei Darussalam'),
	('China'),
	('Denmark'),
	('Dominika'),
	('El Savador'),
	('Filipina'),
	('Finlandia'),
	('Guinea'),
	('Hongaria'),
	('India'),
	('Indonesia'),
	('Irak'),
	('Iran'),
	('Israel'),
	('Italia'),
	('Islandia'),
	('Jamaika'),
	('Jepang'),
	('Jerman'),
	('Kamboja'),
	('Kanada'),
	('Kolombia'),
	('Korea Selatan'),
	('Korea Utara'),
	('Kosta Rika'),
	('Madagaskar'),
	('Malaysia'),
	('Meksiko'),
	('Myanmar'),
	('Nepal'),
	('Nigeria'),
	('Norwegia'),
	('Perancis'),
	('Portugal'),
	('Qatar'),
	('Rusia'),
	('Singapura'),
	('Thailand')

--kota
INSERT INTO Kota (nama_kota, id_negara)
VALUES
	('Kabul', 1),
	('Kandahar', 1),
	('Pretoria', 2),
	('Cape Town', 2),
	('Bangui', 3),
	('Libreville', 3),
	('Tirana', 4),
	('Gramsh', 4),
	('Washington D.C', 5),
	('New York', 5),
	('Canberra', 6),
	('Sydney', 6),
	('Riyadh', 7),
	('Mekkah', 7),
	('Buenos Aires', 8),
	('Rosario', 8),
	('Wina', 9),
	('Baden', 9),
	('Amsterdam', 10),
	('Rotterdam', 10),
	('Brussel', 11),
	('Eeklo', 11),
	('Brasilia', 12),
	('Sao Paolo', 12),
	('Seria', 13),
	('Bandar Seri Begawan', 13),
	('Beijing', 14),
	('Shanghai', 14),
	('Kopenhagen', 15),
	('Aarhus', 15),
	('Santo Domingo', 16),
	('Azua', 16),
	('San Salvador', 17),
	('Santa Ana', 17),
	('Alaminos', 18),
	('Angeles', 18),
	('Helsinki', 19),
	('Espoo', 19),
	('Conakry', 20),
	('Kissidougou', 20),
	('Budapest', 21),
	('Esztergom', 21),
	('Mumbai', 22),
	('New Delhi', 22),
	('jakarta', 23),
	('Bandung', 23),
	('Bagdad', 24),
	('Basra', 24),
	('Isfahan', 25),
	('Ray', 25),
	('Yerusalem', 26),
	('Tel Aviv', 26),
	('Roma', 27),
	('Venesia', 27),
	('Hverageroi', 28),
	('Vik i Myrdal', 28),
	('Kingston', 29),
	('Port Royal', 29),
	('Tokyo', 30),
	('Osaka', 30),
	('Berlin', 31),
	('Hamburg', 31),
	('Phnom Penh', 32),
	('Sihanoukville', 32),
	('Toronto', 33),
	('Kota Quebec', 33),
	('Bogota', 34),
	('Medellin', 34),
	('Seoul', 35),
	('Busan', 35),
	('Pyongyang', 36),
	('Nampo', 36),
	('San Jose', 37),
	('Alajuela', 37),
	('Vohemar', 38),
	('Ambalavao', 38),
	('Kuala Lumpur', 39),
	('Kuching', 39),
	('Guadalajara', 40),
	('Zacatecas', 40),
	('yangoon', 41),
	('Bago', 41),
	('Kathmandu', 42),
	('Patan', 42),
	('Benin City', 43),
	('Lagos', 43),
	('Oslo', 44),
	('Bergen', 44),
	('Paris', 45),
	('Marseille', 45),
	('Lisboa', 46),
	('Porto', 46),
	('Doha', 47),
	('Dukhan', 47),
	('Moskow', 48),
	('Kazan', 48),
	('Rochor', 49),
	('Seletar', 49),
	('Bangkok', 50),
	('Pattaya', 50)

--pengguna
INSERT INTO Pengguna (username, pass)
VALUES 
    ('admin1', 'admin1x'),
    ('admin2', 'admin2x'),
    ('admin3', 'admin3x'),
    ('admin4', 'admin4x'),
    ('admin5', 'admin5x'),
    ('admin6', 'admin6x'),
    ('admin7', 'admin7x'),
    ('admin8', 'admin8x'),
    ('admin9', 'admin9x'),
    ('admin10', 'admin10x')

--administrator
INSERT INTO Administrator (nama, id_pengguna)
VALUES 
	('Admin Vincent', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin1')),
	('Admin Nadia', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin2')),
	('Admin Kevin', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin3')),
    ('Admin Tasha', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin4')),
    ('Admin Kezia', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin5')),
    ('Admin Nando', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin6')),
    ('Admin Jayden', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin7')),
    ('Admin Jason', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin8')),
    ('Admin Kimmy', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin9')),
    ('Admin Rose', (SELECT id_pengguna FROM Pengguna WHERE username = 'admin10'))

--keanggotaan 
INSERT INTO Keanggotaan (nama_keanggotaan, harga, durasi_hari, tanggal_berlaku, id_admin)
VALUES
	('Free', 0, 2147483647, '20220604', 1),
	('VIP', 30000, 30, '20220604', 2),
	('VIP+', 80000, 365, '20220604', 3)

--kategori
INSERT INTO Kategori (nama_kategori)
VALUES
	('Romance'),
	('Action'),
	('Comedy'),
	('Fantasy'),
	('Crime'),
	('Horror'),
	('Thriller'),
	('Religion'),
	('Biography'),
	('Physics'),
	('Geography'),
	('Music'),
	('Sports'),
	('Video Game'),
	('Information Technology'),
	('Engineering'),
	('Mathematics'),
	('Computer Science'),
	('Social Science'),
	('Data Science'),
	('Astrophysics'),
	('Chemistry'),
	('Climate Change'),
	('Electronics'),
	('Health'),
	('Foods'),
	('Music'),
	('Politics'),
	('Content Creating'),
	('Business'),
	('Conspiracy'),
	('Art'),
	('Fashion'),
	('Beauty'),
	('Psychology'),
	('Japanese'),
	('Korean'),
	('Photography'),
	('History'),
	('Fanfiction'),
	('Science Fiction'),
	('Traveling'),
	('Law'),
	('Accounting'),
	('Investment'),
	('Movie'),
	('Architectural'),
	('Education'),
	('Home Living'),
	('Family')